export const FORGOT_PASSWORD_SET_EMAIL:'FORGOT_PASSWORD_SET_EMAIL' = 'FORGOT_PASSWORD_SET_EMAIL';
export const FORGOT_PASSWORD_REQUEST_SUCCESS:'FORGOT_PASSWORD_REQUEST_SUCCESS' = 'FORGOT_PASSWORD_REQUEST_SUCCESS';
export const FORGOT_PASSWORD_REQUEST_FAILED:'FORGOT_PASSWORD_REQUEST_FAILED' = 'FORGOT_PASSWORD_REQUEST_FAILED';
export const FORGOT_PASSWORD_SUBMIT_SUCCESS:'FORGOT_PASSWORD_SUBMIT_SUCCESS' = 'FORGOT_PASSWORD_SUBMIT_SUCCESS';
export const FORGOT_PASSWORD_SUBMIT_FAILED:'FORGOT_PASSWORD_SUBMIT_FAILED' = 'FORGOT_PASSWORD_SUBMIT_FAILED';

export const LOGIN_SUCCESS:'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILED:'LOGIN_FAILED' = 'LOGIN_FAILED';

export const REGISTER_SUCCESS:'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILED:'REGISTER_FAILED' = 'REGISTER_FAILED';

export const TOKEN_REFRESH_SUCCESS:'TOKEN_SUCCESS' = 'TOKEN_SUCCESS';
export const TOKEN_REFRESH_FAILED:'TOKEN_FAILED' = 'TOKEN_FAILED';

export const LOGOUT_SUCCESS:'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED:'LOGOUT_FAILED' = 'LOGOUT_FAILED';

export const GET_USER_SUCCESS:'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_FAILED:'GET_USER_FAILED' = 'GET_USER_FAILED';
export const SET_USER_SUCCESS:'SET_USER_SUCCESS' = 'SET_USER_SUCCESS';
export const SET_USER_FAILED:'SET_USER_FAILED' = 'SET_USER_FAILED';
export const SET_USER_REQUEST:'SET_USER_REQUEST' = 'SET_USER_REQUEST';