export const SUBMIT_ORDER_REQUEST:'SUBMIT_ORDER_REQUEST' = 'SUBMIT_ORDER_REQUEST';
export const SUBMIT_ORDER_SUCCESS:'SUBMIT_ORDER_SUCCESS' = 'SUBMIT_ORDER_SUCCESS';
export const SUBMIT_ORDER_FAILED:'SUBMIT_ORDER_FAILED' = 'SUBMIT_ORDER_FAILED';
export const HIDE_MODAL:'HIDE_MODAL' = 'HIDE_MODAL';