export const WS_CONNECTION_START:'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS:'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR:'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED:'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE:'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const GET_ORDER_BY_ID:'GET_ORDER_BY_ID' = 'GET_ORDER_BY_ID';
export const HIDE_MODAL_FEED:'HIDE_MODAL_FEED' = 'HIDE_MODAL_FEED';
export const SHOW_ORDER_FEED_DETAILS:'SHOW_ORDER_FEED_DETAILS' = 'SHOW_ORDER_FEED_DETAILS';